/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Casilla;
import civitas.CasillaCalle;
import civitas.CivitasJuego;
import civitas.Diario;
import civitas.Jugador;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import javax.swing.JOptionPane;

/**
 *
 * @author antonio
 */
public class CivitasView extends javax.swing.JFrame implements Vista{

    /**
     * Creates new form CivitasView
     */
    
    private CivitasJuego juego;
    
    public CivitasView() {
        initComponents();
    }
    
    public void setCivitasJuego(CivitasJuego civitasjuego){
        juego = civitasjuego;
        setVisible(true);
    }
    
    @Override
    public void actualiza(){
        this.Area_Ranking.setVisible(false);
        this.Ranking.setVisible(false);
        
        Jugador jugador = juego.getJugadorActual();
        this.Datos_jugador.setJugador(jugador);
        
        int indice_casilla = jugador.getCasillaActual();
        
        Casilla casilla = juego.getTablero().getCasilla(indice_casilla);
        
        this.Text_CasillaActual.setText(casilla.toString());
        
        if(juego.finalDelJuego()){
            this.Area_Ranking.setVisible(true);
            this.Ranking.setVisible(true);
            
            this.Area_Ranking.setText(juego.ranking().toString());
        }
        
        repaint();
        revalidate();
        
        
        
    }
    
    @Override
    public void pausa(){
        int val = JOptionPane.showConfirmDialog(null, "¿Continuar?",
                "SiguientePaso", JOptionPane.YES_NO_OPTION);
        
        if(val==1) System.exit(0);
    }
    
    @Override
    public void mostrarEventos(){
       if(!Diario.getInstance().getEventos().isEmpty())
           new DiarioDialog(this);
    }
    
    
    @Override
    public Respuesta comprar(){
        Respuesta respuesta = Respuesta.NO;
        
        int opcion = 1-JOptionPane.showConfirmDialog(null, "¿Quieres comprar la "
                + "calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        
        if(opcion == 0){
            respuesta = Respuesta.NO;
        }
        else if(opcion == 1){
            respuesta = Respuesta.SI;
        }
        
        return respuesta;
        
    }
   
    @Override
    public OperacionInmobiliaria elegirOperacion(){
        
        
        GestionarDialog gestion = new GestionarDialog(this);
        
        int gestionElegida = gestion.getGestion();
        
        OperacionInmobiliaria operacion = OperacionInmobiliaria.values()[gestionElegida];
        
        return operacion;
    }

    @Override
    public int elegirPropiedad(){
        
        PropiedadDialog propiedades = new PropiedadDialog(this, juego.getJugadorActual());
        
        int propiedadElegida = propiedades.getIndicePropiedad();
        
        return propiedadElegida;
        
       
    }

    @Override
    public void mostrarSiguienteOperacion(OperacionJuego operacion){
        this.Text_SiguienteOperacion.setText(operacion.toString());
        
        if(operacion == OperacionJuego.AVANZAR){
            VistaDado.createInstance(this);
        }
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Título = new javax.swing.JLabel();
        Datos_jugador = new GUI.JugadorPanel();
        CasillaActual = new javax.swing.JLabel();
        Text_CasillaActual = new javax.swing.JTextField();
        SiguienteOperacion = new javax.swing.JLabel();
        Text_SiguienteOperacion = new javax.swing.JTextField();
        Ranking = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area_Ranking = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Título.setText("CIVITAS");

        CasillaActual.setText("Casilla Actual");

        Text_CasillaActual.setEditable(false);
        Text_CasillaActual.setText("jTextField1");

        SiguienteOperacion.setText("Siguiente Operación");

        Text_SiguienteOperacion.setEditable(false);
        Text_SiguienteOperacion.setText("jTextField1");

        Ranking.setText("Ranking");

        Area_Ranking.setEditable(false);
        Area_Ranking.setColumns(20);
        Area_Ranking.setRows(5);
        jScrollPane1.setViewportView(Area_Ranking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Título, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CasillaActual)
                        .addGap(18, 18, 18)
                        .addComponent(Text_CasillaActual))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Datos_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SiguienteOperacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Text_SiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ranking)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Título, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Datos_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CasillaActual)
                    .addComponent(Text_CasillaActual, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SiguienteOperacion)
                    .addComponent(Text_SiguienteOperacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Ranking))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area_Ranking;
    private javax.swing.JLabel CasillaActual;
    private GUI.JugadorPanel Datos_jugador;
    private javax.swing.JLabel Ranking;
    private javax.swing.JLabel SiguienteOperacion;
    private javax.swing.JTextField Text_CasillaActual;
    private javax.swing.JTextField Text_SiguienteOperacion;
    private javax.swing.JLabel Título;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
