/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CasillaCalle;

/**
 *
 * @author antonio
 */
public class PropiedadPanel extends javax.swing.JPanel {

    /**
     * Creates new form PropiedadPanel
     */
    
    private CasillaCalle tituloPropiedad;
    
    public PropiedadPanel() {
        initComponents();
    }

    public void setPropiedad(CasillaCalle propiedad){
        tituloPropiedad = propiedad;
        this.Text_nombre.setText(tituloPropiedad.getNombre());
        this.Text_casas.setText(String.valueOf(tituloPropiedad.getNumCasas()));
        this.Text_hoteles.setText(String.valueOf(tituloPropiedad.getNumHoteles()));
        this.Text_precioalquiler.setText(String.valueOf(tituloPropiedad.getPrecioAlquilerCompleto()));
        repaint();
        //revalidate();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Casas = new javax.swing.JLabel();
        Hoteles = new javax.swing.JLabel();
        Text_nombre = new javax.swing.JTextField();
        Text_casas = new javax.swing.JTextField();
        Text_hoteles = new javax.swing.JTextField();
        PrecioAlquiler = new javax.swing.JLabel();
        Text_precioalquiler = new javax.swing.JTextField();

        Nombre.setText("Nombre");

        Casas.setText("Nº Casas");

        Hoteles.setText("Nº Hoteles");

        Text_nombre.setEditable(false);
        Text_nombre.setText("jTextField1");

        Text_casas.setEditable(false);
        Text_casas.setText("jTextField2");

        Text_hoteles.setEditable(false);
        Text_hoteles.setText("jTextField3");

        PrecioAlquiler.setText("Precio Alquiler");

        Text_precioalquiler.setEditable(false);
        Text_precioalquiler.setText("jTextField1");
        Text_precioalquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_precioalquilerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrecioAlquiler)
                        .addGap(18, 18, 18)
                        .addComponent(Text_precioalquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre)
                            .addComponent(Casas)
                            .addComponent(Hoteles))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Text_hoteles, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(Text_casas)
                            .addComponent(Text_nombre))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(Text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casas)
                    .addComponent(Text_casas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hoteles)
                    .addComponent(Text_hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioAlquiler)
                    .addComponent(Text_precioalquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Text_precioalquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_precioalquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_precioalquilerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Casas;
    private javax.swing.JLabel Hoteles;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel PrecioAlquiler;
    private javax.swing.JTextField Text_casas;
    private javax.swing.JTextField Text_hoteles;
    private javax.swing.JTextField Text_nombre;
    private javax.swing.JTextField Text_precioalquiler;
    // End of variables declaration//GEN-END:variables
}
